version: '3.6'
services:
  tigerhall-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiger-dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_PORT: 8080
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: tigerdb
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SUPERUSER_USERNAME: superuser
      SUPERUSER_EMAIL: superuser@tigerhall.com
      SUPERUSER_HASHED_PASSWORD: $$2a$$04$$npZR8DN1y2I0VNRrrPG6XOk.C2lfQLzCOhK5T9lR40oQuecSEHkhm
    networks:
      - tigerhall
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tigerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - tigerhall
    volumes:
      - tigerhall-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

networks:
  tigerhall:
    name: tigerhall-test
    driver: bridge

volumes:
  tigerhall-db: