basePath: /api
definitions:
  request.CreateTigerRequest:
    properties:
      date_of_birth:
        example: "2020-01-01"
        type: string
      last_seen_latitude:
        example: 1.1
        type: number
      last_seen_longitude:
        example: 10.2
        type: number
      last_seen_timestamp:
        example: 1691423085
        type: integer
      name:
        example: tiger name
        type: string
    type: object
  request.CreateTigerSightingRequest:
    properties:
      image:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      timestamp:
        type: integer
    type: object
  request.CreateUserRequest:
    properties:
      email:
        example: user@gmail.com
        type: string
      password:
        example: password
        type: string
      username:
        example: username
        type: string
    type: object
  request.LoginRequest:
    properties:
      email:
        example: user@gmail.com
        type: string
      password:
        example: password
        type: string
    type: object
  response.CreateTigerHandlerResponse:
    properties:
      payload:
        $ref: '#/definitions/response.CreateTigerResponse'
      success:
        example: true
        type: boolean
    type: object
  response.CreateTigerResponse:
    properties:
      date_of_birth:
        example: "2020-01-13"
        type: string
      id:
        type: integer
      last_seen_latitude:
        example: 1.1
        type: number
      last_seen_longitude:
        example: 10.2
        type: number
      last_seen_timestamp:
        example: 1691354650
        type: integer
      name:
        example: tiger name
        type: string
    type: object
  response.CreateTigerSightingHandlerResponse:
    properties:
      payload:
        $ref: '#/definitions/response.CreateTigerSightingResponse'
      success:
        example: true
        type: boolean
    type: object
  response.CreateTigerSightingResponse:
    properties:
      id:
        type: integer
      image:
        example: base64 encoded image string
        type: string
      latitude:
        example: 1.1
        type: number
      longitude:
        example: 10.2
        type: number
      tiger_id:
        example: 1
        type: integer
      timestamp:
        example: 1691354650
        type: integer
    type: object
  response.CreateUserHandlerResponse:
    properties:
      payload:
        $ref: '#/definitions/response.CreateUserResponse'
      success:
        example: true
        type: boolean
    type: object
  response.CreateUserResponse:
    properties:
      email:
        example: user@gmail.com
        type: string
      id:
        example: 1
        type: integer
      username:
        example: username
        type: string
    type: object
  response.ListAllTigersHandlerResponse:
    properties:
      payload:
        $ref: '#/definitions/response.ListAllTigersResponse'
      success:
        example: true
        type: boolean
    type: object
  response.ListAllTigersResponse:
    properties:
      tigers:
        items:
          $ref: '#/definitions/response.TigerResponse'
        type: array
    type: object
  response.LoginHandlerResponse:
    properties:
      payload:
        $ref: '#/definitions/response.LoginResponse'
      success:
        example: true
        type: boolean
    type: object
  response.LoginResponse:
    properties:
      token:
        example: jwt.token
        type: string
    type: object
  response.TigerResponse:
    properties:
      Last_seen_longitude:
        example: 10.2
        type: number
      date_of_birth:
        example: "2020-01-13"
        type: string
      id:
        example: 1
        type: integer
      last_seen_latitude:
        example: 1.1
        type: number
      last_seen_timestamp:
        example: 1691354650
        type: integer
      name:
        example: tiger name
        type: string
      user_id:
        example: 1
        type: integer
    type: object
  utils.HandlerErrorResponse:
    properties:
      error:
        example: Something went wrong
        type: string
      success:
        example: false
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  title: Tigerhall Kittens API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: provides token if email password combination is correct
      parameters:
      - description: login request body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: login api
  /tigers:
    get:
      consumes:
      - application/json
      description: returns all tigers sorted by last time the tiger was seen.
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Page Size
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ListAllTigersHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: list all tigers api
    post:
      consumes:
      - application/json
      description: creates a tiger.
      parameters:
      - description: token received in login api response
        in: header
        name: Authorization
        required: true
        type: string
      - description: create tiger request body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateTigerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateTigerHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: create tiger api
  /tigers/:id/sightings:
    get:
      consumes:
      - application/json
      description: returns all sightings for a tiger sorted by date.
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Page Size
        in: query
        name: pageSize
        required: true
        type: integer
      - description: Tiger ID
        in: path
        name: tigerID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ListAllTigersHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: list all tiger sightings api
    post:
      consumes:
      - application/json
      description: creates a tiger sighting.
      parameters:
      - description: token received in login api response
        in: header
        name: Authorization
        required: true
        type: string
      - description: Tiger ID
        in: path
        name: id
        required: true
        type: integer
      - description: create tiger sighting request body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateTigerSightingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateTigerSightingHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: create tiger sighting api
  /users:
    post:
      consumes:
      - application/json
      description: creates a user.
      parameters:
      - description: token received in login api response
        in: header
        name: Authorization
        required: true
        type: string
      - description: create user request body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateUserHandlerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandlerErrorResponse'
      summary: create user api
schemes:
- http
swagger: "2.0"
